#!/usr/bin/env bash
set -Eeuo pipefail
umask 077

DEPLOY_DIR="${DEPLOY_DIR:-/srv/homeprotectors}"
BACKUP_DIR="${BACKUP_DIR:-/var/lib/homeprotectors/backups}"
ENV_FILE="${ENV_FILE:-$DEPLOY_DIR/.env}"
INFRA_ENV_FILE="${INFRA_ENV_FILE:-/etc/homeprotectors/infra.env}"
PASSPHRASE_FILE="${BACKUP_PASSPHRASE_FILE:-$DEPLOY_DIR/secrets/backup-passphrase}"

if [[ ! -r "$ENV_FILE" || ! -s "$PASSPHRASE_FILE" ]]; then
  echo "Backup environment or encryption passphrase is missing." >&2
  exit 1
fi

if [[ -r "$INFRA_ENV_FILE" ]]; then
  # This file is generated by cloud-init and contains no application secrets.
  # shellcheck disable=SC1090
  source "$INFRA_ENV_FILE"
fi

# Do not source the Docker env file: some legitimate values (such as cron
# expressions) are not shell syntax. Read only the database settings needed here.
BACKUP_DATABASE_URL="${BACKUP_DATABASE_URL:-$(sed -n 's/^BACKUP_DATABASE_URL=//p' "$ENV_FILE" | tail -n 1)}"
PGPASSWORD="${PGPASSWORD:-$(sed -n 's/^DATABASE_PASSWORD=//p' "$ENV_FILE" | tail -n 1)}"
export PGPASSWORD

: "${BACKUP_DATABASE_URL:?Set BACKUP_DATABASE_URL to a postgresql:// Supabase connection URL in .env}"
: "${PGPASSWORD:?Set DATABASE_PASSWORD in .env}"
: "${OCI_BACKUP_BUCKET:?OCI_BACKUP_BUCKET is required}"
: "${OCI_BACKUP_NAMESPACE:?OCI_BACKUP_NAMESPACE is required}"
: "${OCI_REGION:?OCI_REGION is required}"

if [[ "$(pg_dump --version)" != *"PostgreSQL) 17."* ]]; then
  echo "PostgreSQL 17 pg_dump is required for the Supabase database." >&2
  exit 1
fi

mkdir -p "$BACKUP_DIR"
timestamp="$(date -u +%Y%m%dT%H%M%SZ)"
dump_file="$BACKUP_DIR/homeprotectors-$timestamp.dump"
encrypted_file="$dump_file.enc"

cleanup() {
  rm -f -- "$dump_file" "$encrypted_file"
}

notify_failure() {
  exit_code=$?
  trap - ERR
  webhook_url="${BACKUP_FAILURE_WEBHOOK_URL:-$(sed -n 's/^BACKUP_FAILURE_WEBHOOK_URL=//p' "$ENV_FILE" | tail -n 1)}"
  if [[ -n "$webhook_url" ]]; then
    curl --fail --silent --show-error \
      --header 'Content-Type: application/json' \
      --data "{\"text\":\"Homeprotectors database backup failed on $(hostname) at $(date -u +%FT%TZ)\"}" \
      "$webhook_url" || true
  fi
  return "$exit_code"
}

trap cleanup EXIT
trap notify_failure ERR

pg_dump \
  --format=custom \
  --schema=public \
  --no-owner \
  --no-privileges \
  --dbname="$BACKUP_DATABASE_URL" \
  --file="$dump_file"

openssl enc -aes-256-cbc -salt -pbkdf2 -iter 200000 \
  -pass "file:$PASSPHRASE_FILE" \
  -in "$dump_file" \
  -out "$encrypted_file"

oci os object put \
  --auth instance_principal \
  --region "$OCI_REGION" \
  --namespace-name "$OCI_BACKUP_NAMESPACE" \
  --bucket-name "$OCI_BACKUP_BUCKET" \
  --name "database/$(date -u +%Y/%m/%d)/$(basename "$encrypted_file")" \
  --file "$encrypted_file" \
  --force

echo "Encrypted database backup uploaded at $timestamp"
